export interface CityTz { city: string; country: string; tz: string; }

export const CITY_TIMEZONES: CityTz[] = [
  { city: "Almaty",           country: "Kazakhstan",     tz: "Asia/Almaty"          },
  { city: "Astana",           country: "Kazakhstan",     tz: "Asia/Almaty"          },
  { city: "Shymkent",        country: "Kazakhstan",     tz: "Asia/Almaty"          },
  { city: "Aktau",            country: "Kazakhstan",     tz: "Asia/Aqtau"           },
  { city: "Atyrau",           country: "Kazakhstan",     tz: "Asia/Atyrau"          },
  { city: "Tashkent",         country: "Uzbekistan",     tz: "Asia/Tashkent"        },
  { city: "Samarkand",        country: "Uzbekistan",     tz: "Asia/Samarkand"       },
  { city: "Bishkek",          country: "Kyrgyzstan",     tz: "Asia/Bishkek"         },
  { city: "Moscow",           country: "Russia",         tz: "Europe/Moscow"        },
  { city: "Saint Petersburg", country: "Russia",         tz: "Europe/Moscow"        },
  { city: "Yekaterinburg",    country: "Russia",         tz: "Asia/Yekaterinburg"   },
  { city: "Novosibirsk",      country: "Russia",         tz: "Asia/Novosibirsk"     },
  { city: "Krasnoyarsk",      country: "Russia",         tz: "Asia/Krasnoyarsk"     },
  { city: "Irkutsk",          country: "Russia",         tz: "Asia/Irkutsk"         },
  { city: "Vladivostok",      country: "Russia",         tz: "Asia/Vladivostok"     },
  { city: "Dubai",            country: "UAE",            tz: "Asia/Dubai"           },
  { city: "Istanbul",         country: "Turkey",         tz: "Europe/Istanbul"      },
  { city: "Berlin",           country: "Germany",        tz: "Europe/Berlin"        },
  { city: "London",           country: "United Kingdom", tz: "Europe/London"        },
  { city: "Toronto",          country: "Canada",         tz: "America/Toronto"      },
  { city: "Montreal",         country: "Canada",         tz: "America/Toronto"      },
  { city: "Vancouver",        country: "Canada",         tz: "America/Vancouver"    },
  { city: "Calgary",          country: "Canada",         tz: "America/Edmonton"     },
  { city: "New York",         country: "United States",  tz: "America/New_York"     },
  { city: "Los Angeles",      country: "United States",  tz: "America/Los_Angeles"  },
  { city: "Chicago",          country: "United States",  tz: "America/Chicago"      },
];
